// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export type {
  // server loader
  IServerLoaderArgs,
  UmiRequest,
  ServerLoader,
  // metadata loader
  MetadataLoader,
  IMetadata,
  IMetaTag,
} from 'D:/code/ml/foolnet/website/node_modules/@umijs/server/dist/types'
