// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { SiteContext } from 'D:/code/ml/foolnet/website/node_modules/dumi/dist/client/theme-api/context.js';
import { demos, components } from '../meta';
import { locales } from '../locales/config';

const entryExports = {
  
  
};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider value={{
      pkg: {},
      historyType: "browser",
      entryExports,
      demos,
      components,
      locales,
      loading,
      setLoading,
      hostname: undefined,
      themeConfig: {"footer":"Made with ❤️","prefersColor":{"default":"light","switch":true},"nprogress":true,"lastUpdated":true,"name":"FOOLNET","logo":"https://gw.alipayobjects.com/zos/hitu-asset/c88e3678-6900-4289-8538-31367c2d30f2/hitu-1609235995955-image.png","hero":{"zh-CN":{"description":"FOOLNET","actions":[{"type":"primary","text":"开始使用","link":"/guide"},{"text":"Github","link":"https://github.com/","openExternal":true}],"features":[{"title":"巴拉巴拉巴拉","image":"💠","description":"这是一句话","row":6},{"title":"乌西迪西","description":"123","link":"/guide/style","imageType":"light","image":"https://gw.alipayobjects.com/zos/hitu-asset/c88e3678-6900-4289-8538-31367c2d30f2/hitu-1609235995955-image.png","row":9},{"title":"ACDC","link":"/guide/theme","description":"123123","image":"https://mdn.alipayobjects.com/huamei_rqvucu/afts/img/A*8KE7T7l39J0AAAAAAAAAAAAADoN6AQ/original","imageType":"primary"},{"title":"玛卡巴卡","description":"12312312","link":"/guide/syntax-highlighter","image":"https://mdn.alipayobjects.com/huamei_rqvucu/afts/img/A*1qLNRrRGFsQAAAAAAAAAAAAADoN6AQ/original","imageType":"primary","row":9},{"title":"比古比古","description":"123123123","image":"https://mdn.alipayobjects.com/huamei_rqvucu/afts/img/A*6sjjRa7lLhAAAAAAAAAAAAAADoN6AQ/original","imageType":"primary","link":"/components","row":8},{"title":"ToDoList - Welcome to contribution 💪","description":"","image":"💗","imageType":"light","row":6,"hero":true}]},"en-US":{"description":"dumi2 theme similar to antd v5 website","actions":[{"type":"primary","text":"Start","link":"/guide-en"},{"text":"Config","link":"/config-en"}]}},"apiHeader":{"pkg":"foolnet","sourceUrl":"{github}/tree/master/src/components/{atomId}/index.tsx","docUrl":"{github}/tree/master/example/docs/components/{atomId}.{locale}.md"}},
      _2_level_nav_available: true,
    }}>
      {outlet}
    </SiteContext.Provider>
  );
}
