// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true,"hasServerLoader":false,"hasMetadataLoader":false},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"DemoLayout":{"id":"DemoLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/config/index.en-US":{"path":"config-en","id":"docs/config/index.en-US","parentId":"DocLayout"},"docs/config/index.zh-CN":{"path":"config","id":"docs/config/index.zh-CN","parentId":"DocLayout"},"docs/guide/index.en-US":{"path":"guide-en","id":"docs/guide/index.en-US","parentId":"DocLayout"},"docs/guide/index.zh-CN":{"path":"guide","id":"docs/guide/index.zh-CN","parentId":"DocLayout"},"docs/index.en-US":{"path":"-en","id":"docs/index.en-US","parentId":"DocLayout"},"docs/index.zh-CN":{"path":"","id":"docs/index.zh-CN","parentId":"DocLayout"},"docs/changelog":{"path":"changelog","id":"docs/changelog","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"DemoLayout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'D:/code/ml/foolnet/website/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'D:/code/ml/foolnet/website/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-antd-style__dist__layouts__DocLayout__index" */'D:/code/ml/foolnet/website/node_modules/dumi-theme-antd-style/dist/layouts/DocLayout/index.js')),
'DemoLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-antd-style__dist__layouts__DemoLayout__index" */'D:/code/ml/foolnet/website/node_modules/dumi-theme-antd-style/dist/layouts/DemoLayout/index.js')),
'docs/config/index.en-US': React.lazy(() => import(/* webpackChunkName: "docs__config__index.en-US.md" */'D:/code/ml/foolnet/website/docs/config/index.en-US.md')),
'docs/config/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__config__index.zh-CN.md" */'D:/code/ml/foolnet/website/docs/config/index.zh-CN.md')),
'docs/guide/index.en-US': React.lazy(() => import(/* webpackChunkName: "docs__guide__index.en-US.md" */'D:/code/ml/foolnet/website/docs/guide/index.en-US.md')),
'docs/guide/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__guide__index.zh-CN.md" */'D:/code/ml/foolnet/website/docs/guide/index.zh-CN.md')),
'docs/index.en-US': React.lazy(() => import(/* webpackChunkName: "docs__index.en-US.md" */'D:/code/ml/foolnet/website/docs/index.en-US.md')),
'docs/index.zh-CN': React.lazy(() => import(/* webpackChunkName: "docs__index.zh-CN.md" */'D:/code/ml/foolnet/website/docs/index.zh-CN.md')),
'docs/changelog': React.lazy(() => import(/* webpackChunkName: "docs__changelog.md" */'D:/code/ml/foolnet/website/docs/changelog.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'D:/code/ml/foolnet/website/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
