// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/code/ml/foolnet/website/node_modules/dumi/theme-default/slots/HeroTitle/index.js';
